[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#E5E5E5"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
